### ISSUE TITLE
initialization errored: Unexpected token export

### ISSUE THREAD

**Issue by danifbento** [aheissenberger/serverless-appsync-offline#11]
Hello,

I'm trying to run serverless-appsync-offline but I'm getting the following error:

> "Serverless plugin "serverless-appsync-offline" initialization errored: Unexpected token export"

I already updated `nodejs` to `v11.6.0` version and `npm` to `6.5.0-next.0`

Do you have any idea why this is happening?

**Comment by danifbento** [comment]
I found that running a `npm install && npm run prepare` inside `graphql-phone-type` it stops giving this error...

**Comment by timgivois** [comment]
can you give more context?

**Comment by austin43** [comment]
@danifbento @timgivois we are running into the same issue using the [pnpm](https://pnpm.js.org) packager.  Running npm install in the package directory at least gets us past this error.
```
cd node_modules/serverless-appsync-offline;
npm install;
```
It seems when using pnpm, we run into an issue during install of this package because prepare fails for graphql-phone-type: 
```
ERROR  graphql-phone-type@0.0.2 prepare: `npm run clean && npm run lint && npm run build`
Exit status 1
```
